# Generated by Django 4.2.7 on 2025-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código estudiantil o número de identificación', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='programa',
            field=models.CharField(blank=True, help_text='Programa o facultad a la que pertenece', max_length=100, null=True),
        ),
    ]
