# Generated by Django 4.2.7 on 2025-02-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_remove_usuario_dependencia_usuario_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dependencia_admin',
            field=models.ForeignKey(blank=True, help_text='Dependencia que administra (solo para administradores)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='prestamos.dependencia'),
        ),
    ]
