# Generated by Django 4.2.7 on 2025-02-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_usuario_dependencia_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(help_text='Código estudiantil o número de identificación', max_length=20, unique=True),
        ),
    ]
