# Generated by Django 4.2.7 on 2025-03-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_remove_recurso_color_recurso_tipo_alter_recurso_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
