# Generated by Django 4.2.7 on 2025-03-12 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prestamos', '0008_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dependencia_admin',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='administrador',
            field=models.OneToOneField(blank=True, help_text='Administrador de la dependencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencia_administrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(related_name='usuarios_personalizados', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(related_name='usuarios_personalizados', to='auth.permission'),
        ),
    ]
