# Generated by Django 4.2.7 on 2025-03-14 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
